### ISSUE TITLE
gwmi isn't available on Powershell 7

### ISSUE THREAD

**Issue by vstiebe** [fdcastel/Hyper-V-Automation#12]
When running the New-VMFromUbuntuImage.ps1 I got the following message:

`New-VMFromUbuntuImage.ps1: The term 'gwmi' is not recognized as a name of a cmdlet, function, script file, or executable program.`

https://answers.microsoft.com/en-us/windows/forum/all/getting-error-that-gwmi-is-not-recognised-as-a/2b01f763-c109-4757-b992-e5b281472367

**Comment by fdcastel** [comment]
Thanks. I should not have used the aliased version of the commands.

**Comment by fdcastel** [comment]
Also, for Windows images, this project heavily relies on [`Convert-WindowsImage.ps1`](https://github.com/fdcastel/Hyper-V-Automation/blob/master/tools/Convert-WindowsImage.ps1), an ancient script from Microsoft that is now largely unmaintained. Unfortunately this script does not work in Powershell 6.0+ ("Core").

I'll add a `#requires` clause to inform future users about this limitation.

**Comment by fdcastel** [comment]
Fixed in latest `master`.
