### ISSUE TITLE
More of a heads up than an issue, oscdimg.exe doesn't like clustered storage

### ISSUE THREAD

**Issue by czuk** [fdcastel/Hyper-V-Automation#13]
I installed the Hyper-V-Automation repo onto one of our cluster nodes and tried creating a new Ubuntu VM and got the following error from oscdimg.exe:

WriteFile failed (C:\ClusterStorage\Volume1\Hyper-V\test.iso, off=D800 len=1000 status=103)
Error 87: The parameter is incorrect.

It works perfectly if the Hyper-V default storage isn't on clustered storage.  A potential workaround is to create the iso in local temp folder and attach that to the VM. e.g.

New-VMFromUbuntuImage.ps1 line 112

replace
$metadataIso = Join-Path $vmmsSettings.DefaultVirtualHardDiskPath "$VMName-metadata.iso"
with
$metadataIso = Join-Path ([System.IO.Path]::GetTempPath()) "$VMName-metadata.iso"

**Comment by fdcastel** [comment]
Thank you, @czuk, for bringing this to my attention. 

Would you happen to know a reliable method for determining if a given path is under clustered storage? 

Unfortunately, I have no access to any cluster installations for testing.

**Comment by czuk** [comment]
The configuration we are using is Storage Spaces Direct (S2D) and the clustered storage was created after the failover cluster was created by running the powershell cmdlet Enable-ClusterStorageSpacesDirect.  

I've been searching online, and I can't find any way of changing the clustered storage path from C:\ClusterStorage so that might work as a valid check.

The workaround I suggested does the job though, and the metadata ISO gets deleted after use so it doesn't really matter where it gets created as long as Hyper-V can access it.

**Comment by fdcastel** [comment]
> The workaround I suggested does the job though, and the metadata ISO gets deleted after use so it doesn't really matter where it gets created as long as Hyper-V can access it.

Of course! Excellent observation. 

I will implement this change.

**Comment by fdcastel** [comment]
@czuk, could you please test the latest version I just pushed? I believe it should now address the issue on your end.

**Comment by czuk** [comment]
@fdcastel New-VMFromUbuntuImage.ps1 is working as expected but New-VMFromDebianImage.ps1 gives:
VERBOSE: Creating VHDX from cloud image...
VERBOSE: Creating VM...
VERBOSE: Waiting for MAC addresses...
VERBOSE: Creating metadata ISO image...
VERBOSE: Metadata ISO created: C:\Users\adminuser\AppData\Local\Temp\testdebian-metadata.iso
VERBOSE: Waiting for VM integration services (1)...

But that looks like an issue with Debian?

.\Get-DebianImage.ps1 returns:
C:\Scripts\Hyper-V-Automation-master\debian-12-genericcloud-amd64.qcow2

Anything you want me to do?

**Comment by czuk** [comment]
A bit more info, I left the VM alone for a bit because I had other stuff to do, when I came back the console showed a kernel panic, I reset the VM, it rebooted and the powershell continued on from the waiting for integration stage:

VERBOSE: Waiting for VM integration services (1)...
VERBOSE: Waiting for VM initial setup...
VERBOSE: Waiting for VM integration services (2)...
VERBOSE: All done!

This does look like a Debian issue though - panic screenshot here
![image](https://github.com/user-attachments/assets/2bcab00c-49f3-4167-a054-6ceb2fc13e7d)

**Comment by fdcastel** [comment]
Interesting... I had tested this with both Debian and Ubuntu images before the publish.

However, I may have used an outdated version of the image, which was downloaded several months ago. 

I will look into this further later tonight. But, yes, it seems to be a problem with latest Debian image.

**Comment by fdcastel** [comment]
BTW: Could you provide the exact configuration you used for the VM?

(the full command line used for the `New-VMFromDebianImage.ps1` call)

**Comment by fdcastel** [comment]
Sorry @czuk. I’ve been unable to reproduce the issue even using the latest Debian cloud image.

A quick research about the error suggests that the problem might be related to low available resources. However, I was able to successfully launch a VM with just 512MB of RAM and a single vCPU.

Even with 256MB of RAM, the VM started without a kernel panic. However, in this case, the Out-Of-Memory (OOM) killer had kicked in:

![image](https://github.com/user-attachments/assets/3b669f9b-34c6-4bb8-86b6-4e60ff31350f)

**Comment by czuk** [comment]
Full command line is:
.\New-VMFromDebianImage.ps1 -SourcePath C:\Scripts\Hyper-V-Automation-master\debian-12-genericcloud-amd64.qcow2 -VMName testdebian01 -FQDN testdebian.domain.com -RootPublicKey "redacted" -VHDXSizeBytes 300GB -MemoryStartupBytes 8GB -ProcessorCount 4 -IPAddress 10.0.0.115/16 -Gateway 10.0.0.254 -DnsAddresses "10.0.0.1, 10.0.0.2" -Verbose -SwitchName "SWITCH"

**Comment by fdcastel** [comment]
Your command line seems perfectly fine. 

Are you still having the same problem? Did you try to download a more recent Debian image?
