### ISSUE TITLE
New-VMFromWindowsImage returns an object array; instead an actual VM object

### ISSUE THREAD

**Issue by rkttu** [fdcastel/Hyper-V-Automation#4]
When I run the New-VMFromWindowsImage.ps1 in the Windows PowerShell with below script, the .ps1 cmdlet returns an object array, instead an actual VM object.

In the code, the script intends to return an object with created by New-VM cmdlet, so I expected the New-VMFromWindowsImage will return an single VM object. But when I tried, different results found.

Ref: https://github.com/fdcastel/Hyper-V-Automation/blob/master/New-VMFromWindowsImage.ps1#L55

```powershell
Add-Type -AssemblyName 'System.Web'
$AdminPwd = "$([System.Web.Security.Membership]::GeneratePassword(32, 16))"
Write-Host "Administrator Password: $AdminPwd"

$VMSwitch = (Get-VMSwitch | Where-Object { $_.Name -like '*Default*' -or $_.Name -like '*기본*' })[0].Name

$VMName = 'WinServer2016'
$OSVersion = 'Server2016Datacenter'
$ProcessorCount = 2
$DiskSizeInGB = 128
$InitialMemSizeInMB = 2048

$VHDXSizeBytes = [Math]::Round([Convert]::ToInt32($DiskSizeInGB) * 1073741824, 0)
$MemStartupBytes = [Math]::Round([Convert]::ToInt32($InitialMemSizeInMB) * 1048576, 0)

$vm = .\New-VMFromWindowsImage.ps1 `
  -SourcePath 'C:\OS\en_windows_server_version_1709_updated_jan_2018_x64_dvd.iso' `
  -Edition '1' `
  -VMName $VMName `
  -VHDXSizeBytes $VHDXSizeBytes `
  -AdministratorPassword $AdminPwd `
  -Version $OSVersion `
  -MemoryStartupBytes $MemStartupBytes `
  -VMProcessorCount $ProcessorCount `
  -VMSwitchName $VMSwitch `
  -Locale 'en-US' `
  -EnableDynamicMemory
```

![image](https://user-images.githubusercontent.com/1297346/113104036-01736e80-923b-11eb-83d8-b12d7db5b98f.png)

**Comment by fdcastel** [comment]
Cannot reproduce, sorry. It's a very strange case, indeed.

[`New-VM` documentation](https://docs.microsoft.com/en-us/powershell/module/hyper-v/new-vm?view=windowsserver2019-ps#outputs) if very clear about the fact that the output is a scalar value and not an array.
