### ISSUE TITLE
Suggestion: Add the ubuntu user to the docker-group

### ISSUE THREAD

**Issue by Da-Teach** [fdcastel/Hyper-V-Automation#7]
See:
https://www.digitalocean.com/community/questions/how-to-fix-docker-got-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket

Easy fix:
```
if ($InstallDocker) {
    $sectionRunCmd += @'

 - 'apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common'
 - 'curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -'
 - 'add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"'
 - 'apt update -y'
 - 'apt install -y docker-ce docker-ce-cli containerd.io docker-compose'
 - 'usermod -aG docker ubuntu'
'@
} 
````

**Comment by fdcastel** [comment]
Relevant discussion:
    https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo

Also:
    https://fosterelli.co/privilege-escalation-via-docker.html

The current steps used are taken from the official docker docs:
    https://docs.docker.com/engine/install/ubuntu/

I believe it would be better to keep the official steps and leave to each
user whether to go or not to the next level.
