### ISSUE TITLE
Feature request: Allow additional commands to be run after installation

### ISSUE THREAD

**Issue by Da-Teach** [fdcastel/Hyper-V-Automation#8]
It would be amazing to allow the scripts (well in my personal case the Ubuntu image generation) to run additional commands. 

It could be used to install additional packages, setup fstab, create mount folders, etc. 

This way it's easier to create a fully automated server install.

**Comment by fdcastel** [comment]
Just one question: Why?

The script `New-VMFromUbuntuImage.ps1` returns only when the VM is responding and ready to use.

At this point you can run all your additional commands via ssh.

DISCLAIMER: That's exactly what I do. 😉
